/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as QueuesQueueNameRouteRouteImport } from './routes/queues/$queueName/route'
import { Route as QueuesQueueNameIndexRouteImport } from './routes/queues/$queueName/index'
import { Route as QueuesQueueNameFlowsRouteImport } from './routes/queues/$queueName/flows'
import { Route as QueuesQueueNameJobsRouteImport } from './routes/queues/$queueName/jobs'
import { Route as QueuesQueueNameSchedulersRouteImport } from './routes/queues/$queueName/schedulers'
import { Route as QueuesQueueNameWorkersRouteImport } from './routes/queues/$queueName/workers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const QueuesQueueNameRouteRoute = QueuesQueueNameRouteRouteImport.update({
  id: '/queues/$queueName',
  path: '/queues/$queueName',
  getParentRoute: () => rootRouteImport,
} as any)
const QueuesQueueNameIndexRoute = QueuesQueueNameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QueuesQueueNameRouteRoute,
} as any)
const QueuesQueueNameFlowsRoute = QueuesQueueNameFlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => QueuesQueueNameRouteRoute,
} as any)
const QueuesQueueNameJobsRoute = QueuesQueueNameJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => QueuesQueueNameRouteRoute,
} as any)
const QueuesQueueNameSchedulersRoute =
  QueuesQueueNameSchedulersRouteImport.update({
    id: '/schedulers',
    path: '/schedulers',
    getParentRoute: () => QueuesQueueNameRouteRoute,
  } as any)
const QueuesQueueNameWorkersRoute = QueuesQueueNameWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => QueuesQueueNameRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/queues/$queueName': typeof QueuesQueueNameRouteRouteWithChildren
  '/queues/$queueName/flows': typeof QueuesQueueNameFlowsRoute
  '/queues/$queueName/jobs': typeof QueuesQueueNameJobsRoute
  '/queues/$queueName/schedulers': typeof QueuesQueueNameSchedulersRoute
  '/queues/$queueName/workers': typeof QueuesQueueNameWorkersRoute
  '/queues/$queueName/': typeof QueuesQueueNameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/queues/$queueName/flows': typeof QueuesQueueNameFlowsRoute
  '/queues/$queueName/jobs': typeof QueuesQueueNameJobsRoute
  '/queues/$queueName/schedulers': typeof QueuesQueueNameSchedulersRoute
  '/queues/$queueName/workers': typeof QueuesQueueNameWorkersRoute
  '/queues/$queueName': typeof QueuesQueueNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/queues/$queueName': typeof QueuesQueueNameRouteRouteWithChildren
  '/queues/$queueName/flows': typeof QueuesQueueNameFlowsRoute
  '/queues/$queueName/jobs': typeof QueuesQueueNameJobsRoute
  '/queues/$queueName/schedulers': typeof QueuesQueueNameSchedulersRoute
  '/queues/$queueName/workers': typeof QueuesQueueNameWorkersRoute
  '/queues/$queueName/': typeof QueuesQueueNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/queues/$queueName'
    | '/queues/$queueName/flows'
    | '/queues/$queueName/jobs'
    | '/queues/$queueName/schedulers'
    | '/queues/$queueName/workers'
    | '/queues/$queueName/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/queues/$queueName/flows'
    | '/queues/$queueName/jobs'
    | '/queues/$queueName/schedulers'
    | '/queues/$queueName/workers'
    | '/queues/$queueName'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/queues/$queueName'
    | '/queues/$queueName/flows'
    | '/queues/$queueName/jobs'
    | '/queues/$queueName/schedulers'
    | '/queues/$queueName/workers'
    | '/queues/$queueName/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  QueuesQueueNameRouteRoute: typeof QueuesQueueNameRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queues/$queueName': {
      id: '/queues/$queueName'
      path: '/queues/$queueName'
      fullPath: '/queues/$queueName'
      preLoaderRoute: typeof QueuesQueueNameRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queues/$queueName/': {
      id: '/queues/$queueName/'
      path: '/'
      fullPath: '/queues/$queueName/'
      preLoaderRoute: typeof QueuesQueueNameIndexRouteImport
      parentRoute: typeof QueuesQueueNameRouteRoute
    }
    '/queues/$queueName/flows': {
      id: '/queues/$queueName/flows'
      path: '/flows'
      fullPath: '/queues/$queueName/flows'
      preLoaderRoute: typeof QueuesQueueNameFlowsRouteImport
      parentRoute: typeof QueuesQueueNameRouteRoute
    }
    '/queues/$queueName/jobs': {
      id: '/queues/$queueName/jobs'
      path: '/jobs'
      fullPath: '/queues/$queueName/jobs'
      preLoaderRoute: typeof QueuesQueueNameJobsRouteImport
      parentRoute: typeof QueuesQueueNameRouteRoute
    }
    '/queues/$queueName/schedulers': {
      id: '/queues/$queueName/schedulers'
      path: '/schedulers'
      fullPath: '/queues/$queueName/schedulers'
      preLoaderRoute: typeof QueuesQueueNameSchedulersRouteImport
      parentRoute: typeof QueuesQueueNameRouteRoute
    }
    '/queues/$queueName/workers': {
      id: '/queues/$queueName/workers'
      path: '/workers'
      fullPath: '/queues/$queueName/workers'
      preLoaderRoute: typeof QueuesQueueNameWorkersRouteImport
      parentRoute: typeof QueuesQueueNameRouteRoute
    }
  }
}

interface QueuesQueueNameRouteRouteChildren {
  QueuesQueueNameFlowsRoute: typeof QueuesQueueNameFlowsRoute
  QueuesQueueNameJobsRoute: typeof QueuesQueueNameJobsRoute
  QueuesQueueNameSchedulersRoute: typeof QueuesQueueNameSchedulersRoute
  QueuesQueueNameWorkersRoute: typeof QueuesQueueNameWorkersRoute
  QueuesQueueNameIndexRoute: typeof QueuesQueueNameIndexRoute
}

const QueuesQueueNameRouteRouteChildren: QueuesQueueNameRouteRouteChildren = {
  QueuesQueueNameFlowsRoute: QueuesQueueNameFlowsRoute,
  QueuesQueueNameJobsRoute: QueuesQueueNameJobsRoute,
  QueuesQueueNameSchedulersRoute: QueuesQueueNameSchedulersRoute,
  QueuesQueueNameWorkersRoute: QueuesQueueNameWorkersRoute,
  QueuesQueueNameIndexRoute: QueuesQueueNameIndexRoute,
}

const QueuesQueueNameRouteRouteWithChildren =
  QueuesQueueNameRouteRoute._addFileChildren(QueuesQueueNameRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  QueuesQueueNameRouteRoute: QueuesQueueNameRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
